# Generated by Django 6.0.2 on 2026-02-27 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255, unique=True, verbose_name='Vehículo (Marca, Modelo, Año)')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('calidad', models.CharField(choices=[('Nacional', 'Nacional'), ('Importado', 'Importado')], default='Nacional', max_length=20)),
                ('caracteristicas', models.TextField(blank=True, help_text='Separa cada característica con una coma', null=True)),
                ('en_oferta', models.BooleanField(default=False, verbose_name='¿Está en oferta?')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial para la sección de ofertas', max_digits=10, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.categoria')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVehiculo',
            fields=[
                ('pk', models.CompositePrimaryKey('id_producto', 'id_vehiculo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='products.producto')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='products.vehiculo')),
            ],
            options={
                'db_table': 'producto_vehiculo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='vehiculos',
            field=models.ManyToManyField(related_name='productos', through='products.ProductoVehiculo', to='products.vehiculo', verbose_name='Modelos compatibles'),
        ),
    ]
