# Generated by Django 6.0.2 on 2026-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productovehiculo',
            unique_together={('id_producto', 'id_vehiculo')},
        ),
        migrations.AddField(
            model_name='productovehiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='productovehiculo',
            name='pk',
        ),
    ]
