# Generated by Django 6.0 on 2026-03-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
