# Generated by Django 6.0 on 2026-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
