# Generated by Django 6.0 on 2026-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usuario_email_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='tmp_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
